{% set version = "0.24.0" %}

package:
  name: asn1crypto
  version: {{ version }}

source:
  fn: asn1crypto-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/a/asn1crypto/asn1crypto-{{ version }}.tar.gz
  sha256: 9d5c20441baf0cb60a4ac34cc447c6c189024b6b4c6cd7877034f4965c464e49

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - asn1crypto

about:
  home: https://github.com/wbond/asn1crypto
  license: MIT
  # https://github.com/wbond/asn1crypto/issues/58
  #license_file: LICENSE
  summary: Python ASN.1 library with a focus on performance and a pythonic API

extra:
  recipe-maintainers:
    - jschueller
