{% set version = "1.1.1" %}

package:
  name: sympy
  version: {{ version }}

source:
  fn: sympy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/sympy/sympy-{{ version }}.tar.gz
  md5: c410a9c2346878716d16ec873d72e72a

build:
  number: 0
  noarch: python
  script: python setup.py install

requirements:
  build:
    - fastcache
    - mpmath
    - python
  run:
    - fastcache
    - mpmath >=0.19
    - python

test:
  commands:
    - isympy -help
  imports:
    - sympy

about:
  home: http://sympy.org
  license: 3-clause BSD
  license_family: BSD
  license_file: LICENSE
  summary: Python library for symbolic mathematics
  description: |
    SymPy is a Python library for symbolic mathematics. It aims to become a
    full-featured computer algebra system (CAS) while keeping the code as
    simple as possible in order to be comprehensible and easily extensible.
  doc_url: http://docs.sympy.org/latest/index.html
  dev_url: https://github.com/sympy/sympy
