{% set version = "1.2" %}

package:
  name: sympy
  version: {{ version }}

source:
  fn: sympy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/sympy/sympy-{{ version }}.tar.gz
  md5: 11b24840f5740bb03feddb7d60c18a67

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - fastcache
    - mpmath
    - python
  run:
    - fastcache
    - mpmath >=0.19
    - python
    - gmpy2 >=2.0.8   # [not win]

test:
  commands:
    - isympy --help
  imports:
    - sympy

about:
  home: http://sympy.org
  license: 3-clause BSD
  license_family: BSD
  license_file: LICENSE
  summary: Python library for symbolic mathematics
  description: |
    SymPy is a Python library for symbolic mathematics. It aims to become a
    full-featured computer algebra system (CAS) while keeping the code as
    simple as possible in order to be comprehensible and easily extensible.
  doc_url: http://docs.sympy.org/latest/index.html
  dev_url: https://github.com/sympy/sympy

extra:
  recipe-maintainers:
    - asmeurer
    - msarahan
    - scopatz
