{% set version = "0.2.0" %}

package:
  name: locket
  version: {{ version }}

source:
  fn: locket-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/l/locket/locket-{{ version }}.tar.gz
  md5: fe870949c513d8f7079ba352463833ca

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - locket

about:
  home: https://github.com/mwilliamson/locket.py
  license: BSD 2-Clause
  license_file: LICENSE
  summary: File-based locks for Python for Linux and Windows
