package:
  name: bokeh
  version: 0.12.5

source:
  fn: bokeh-0.12.5.tar.gz
  url: https://pypi.python.org/packages/6c/f5/6a4b75f5f7c35771b172994c5b5642dd0f923d781b8eb7a9167339eb63b4/bokeh-0.12.4.tar.gz
  md5: 82eb8e8b7a5fe7ce727b8a6ab1e4b5da

build:
  number: 0
  entry_points:
    - bokeh = bokeh.__main__:main

requirements:
  build:
    - python
  run:
    - python
    - six >=1.5.2
    - requests >=1.2.3
    - pyyaml >=3.10
    - python-dateutil >=2.1
    - jinja2 >=2.7
    - numpy
    - tornado >=4.3
    - futures >=3.0.3        [py27]

test:
  commands:
    - bokeh -h
  imports:
    - bokeh
    - bokeh.application
    - bokeh.models
    - bokeh.models.widgets
    - bokeh.sampledata
    - bokeh.server
    - bokeh.sphinxext
    - bokeh.util

about:
  home: http://bokeh.pydata.org/
  license: BSD
  license_file: LICENSE.txt
  summary: Python interactive visualization library for modern web browsers
  description: |
    Bokeh is a Python interactive visualization library that targets
    modern web browsers for presentation. Its goal is to provide elegant,
    concise  construction of novel graphics in the style of D3.js, and to
    extend this capability with high-performance interactivity over very
    large or streaming datasets. Bokeh can help anyone who would like to
    quickly and easily create interactive plots, dashboards, and data
    applications.
  doc_url: http://bokeh.pydata.org/en/latest/docs/user_guide.html
  dev_url: http://github.com/bokeh/bokeh
