{% set name = "setuptools" %}
{% set version = "36.2.7" %}

package:
  name: setuptools
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: b0fe5d432d922df595e918577c51458d63f245115d141b309ac32ecfca329df5
  patches:
    # Modify setuptools to fail if used in conda build (encourage people to add all deps in meta.yaml).
    - nodownload.patch

build:
  number: 0
  entry_points:
    - easy_install = setuptools.command.easy_install:main

requirements:
  build:
    - python
    - certifi
  run:
    - python
    - certifi

test:
  commands:
    - easy_install --help
  imports:
    - setuptools
    - easy_install
    - pkg_resources

about:
  home: https://github.com/pypa/setuptools
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Download, build, install, upgrade, and uninstall Python packages
  description: |
    Setuptools is a fully-featured, actively-maintained, and stable library
    designed to facilitate packaging Python projects.
  doc_url: http://pythonhosted.org/setuptools/
  dev_url: https://github.com/pypa/setuptools
