{% set name = "lzo" %}
{% set version = "2.10" %}
{% set version_major = "2" %}
{% set hash_type = "sha256" %}
{% set hash_val = "c0f892943208266f9b6543b3ae308fab6284c5c90e627931446fb49b4221a072" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.oberhumer.com/opensource/{{ name }}/download/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  skip: True  # [win and py35]
  features:
    - vc9   # [win and py27]
    - vc14  # [win and py36]

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - cmake 3.*

  host:
    - python     # [win]
    - vc 9       # [win and py27]
    - vc 14      # [win and py36]

  run:
    - vc 9       # [win and py27]
    - vc 14      # [win and py36]

test:
  commands:
    - test -f ${PREFIX}/include/lzo/lzoconf.h                                 # [unix]
    - test -f ${PREFIX}/lib/liblzo{{ version_major }}.a                       # [unix]
    - test -f ${PREFIX}/lib/liblzo{{ version_major }}.dylib                   # [osx]
    - test -f ${PREFIX}/lib/liblzo{{ version_major }}.so                      # [linux]

    - if not exist %PREFIX%\\Library\\include\\lzo\\lzoconf.h exit 1          # [win]
    - if not exist %PREFIX%\\Library\\lib\\lzo{{ version_major }}.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\lzo{{ version_major }}_dllimport.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\lzo{{ version_major }}.dll exit 1  # [win]

    - conda inspect linkages -p $PREFIX {{ name }}                            # [unix]
    - conda inspect objects -p $PREFIX {{ name }}                             # [osx]

about:
  home: http://www.oberhumer.com/opensource/lzo/
  license: GPL v2+
  license_file: COPYING
  summary: LZO is a portable lossless data compression library written in ANSI C.

extra:
  recipe-maintainers:
    - rmax
