{% set version = "6.3" %}

package:
  name: readline
  version: {{ version }}

source:
  url: ftp://ftp.gnu.org/gnu/readline/readline-{{ version }}.tar.gz
  fn: readline-{{ version }}.tar.gz
  md5: 33c8fb279e981274f485fd91da77e94a
  patches:
    - patches/readline63-001
    - patches/readline63-002
    - patches/readline63-003
    - patches/readline63-004
    - patches/readline63-005
    - patches/readline63-006
    - patches/readline63-007
    - patches/readline63-008

build:
  number: 0

requirements:
  build:
    - ncurses 5.9*
  run:
    - ncurses 5.9*

test:
  commands:
  {% set readline_libs = [
    'libreadline',
    'libhistory'
  ] %}
  {% for lib in readline_libs %}
    - test -f ${PREFIX}/lib/{{ lib }}.a
    - test -f ${PREFIX}/lib/{{ lib }}.so
  {% endfor %}

about:
  home: https://cnswww.cns.cwru.edu/php/chet/readline/rltop.html
  license: GPL3
  summary: library for editing command lines as they are typed in
