{% set version = "5.1.1" %}

package:
  name: nbconvert
  version: {{ version }}

source:
  fn: nbconvert-{{ version }}.tar.gz
  url: https://github.com/jupyter/nbconvert/archive/{{ version }}.tar.gz
  sha256: 1502366caab4f1aa86adebc9def492448f69310c88e52d0998c8edf2d97617ad

build:
  number: 0
  script: pip install --no-deps .
  entry_points:
    - jupyter-nbconvert = nbconvert.nbconvertapp:main

requirements:
  build:
    - python
    - pip
  run:
    - bleach
    - entrypoints >=0.2.2
    - jinja2
    - jupyter_core
    - mistune >0.6
    - nbformat
    #- pandoc
    - pandocfilters >=1.4.1
    - python
    - pygments
    - testpath
    - traitlets

test:
  imports:
    - nbconvert
    - nbconvert.exporters
    - nbconvert.filters
    - nbconvert.postprocessors
    - nbconvert.preprocessors
    - nbconvert.resources
    - nbconvert.tests
    - nbconvert.utils
    - nbconvert.writers

  commands:
    - jupyter-nbconvert --help

about:
  home: http://jupyter.org
  license: BSD 3-Clause
  summary: 'Converting Jupyter Notebooks'
