{% set version = "3.8.0" %}

package:
  name: lxml
  version: {{ version }}

source:
  fn: lxml-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/l/lxml/lxml-{{ version }}.tar.gz
  sha256: 736f72be15caad8116891eb6aa4a078b590d231fdc63818c40c21624ac71db96

build:
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record record.txt --with-xslt-config=$PREFIX/bin/xslt-config

requirements:
  build:
    - python
    - setuptools
    - cython
    - libxml2 2.9.*
    - libxslt
  run:
    - python
    - libxml2 2.9.*
    - libxslt

test:
  imports:
    - lxml
    - lxml.etree
    - lxml.objectify
  commands:
    - conda inspect linkages -p $PREFIX lxml

about:
  home: http://lxml.de/
  license: BSD 3-Clause, GPL-2.0, ZPL-2.0, and ElementTree
  license_file: LICENSES.txt
  summary: 'Pythonic binding for the C libraries libxml2 and libxslt.'
  description: |
    The lxml XML toolkit is a Pythonic binding for the C libraries libxml2 and
    libxslt. It is unique in that it combines the speed and XML feature
    completeness of these libraries with the simplicity of a native Python API,
    mostly compatible but superior to the well-known ElementTree API.
  doc_url: 'http://lxml.de/index.html#documentation'
  dev_url: https://github.com/lxml/lxml
