{% set version = "4.5.11" %}
{% set checksum = "99080c5fc43a76ae7dc082943a793a62cb3d4ec66f3986ff0216d22f1594401f" %}

package:
  name: conda
  version: {{ version }}

source:
  url: https://github.com/conda/conda/archive/{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  # These are present when the new environment is created
  # so we have to exempt them from the list of initial files
  # for conda-build to realize they should be included.
  entry_points:
    - conda = conda.cli:main
    - conda-env = conda_env.cli.main:main
  always_include_files:
    - bin/conda                            # [unix]
    - bin/activate                         # [unix]
    - bin/deactivate                       # [unix]
    - Scripts/activate.bat                 # [win]
    - Scripts/activate                     # [win]
    - Scripts/deactivate.bat               # [win]
    - Scripts/deactivate                   # [win]

requirements:
  build:
    - python
    - m2-base              # [win]
    - m2-filesystem        # [win]
    - m2-git               # [win]
  run:
    - python
    - conda-env >=2.6
    - enum34                 # [py<34]
    - futures >=3.0.0        # [py<34]
    - menuinst               # [win]
    - pycosat >=0.6.3
    - pyopenssl >=16.2.0
    - requests >=2.12.4,<3
    - ruamel_yaml >=0.11.14  # [py>27]
    - ruamel_yaml >=0.11.14,<0.15.39|>=0.15.43  # [py<=27]
  run_constrained:
    - conda-build >=2.1
    - cytoolz >=0.8.1
    - setuptools >=31.0.1

test:
  files:
    - test_conda.bat                # [win]
    - test_conda.sh                 # [unix]

  imports:
    - conda

about:
  home: https://conda.io
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: OS-agnostic, system-level binary package and environment manager.
  description: |
    Conda is an open source package management system and environment
    management system for installing multiple versions of software packages
    and their dependencies and switching easily between them. It works on
    Linux, OS X and Windows, and was created for Python programs but can
    package and distribute any software.
  doc_url: https://conda.io/docs/
  dev_url: https://github.com/conda/conda

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
    - mbargull
