{% set version = "1.2.11" %}

package:
    name: zlib
    version: {{ version }}

source:
    fn: zlib-{{ version }}.tar.gz
    url: http://zlib.net/zlib-{{ version }}.tar.gz
    sha256: c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1

build:
    number: 0

test:
    commands:
        - test -f ${PREFIX}/lib/libz.a

about:
    home: http://zlib.net/
    license: zlib (http://zlib.net/zlib_license.html)
    summary: Massively spiffy yet delicately unobtrusive compression library
    license_family: Other
    license_file: license.txt
