{% set version = "0.18.2" %}

package:
  name: dask
  version: "{{ version }}"

build:
  number: 0
  noarch: python

requirements:
  build:
    - python

  run:
    - python
    - bokeh
    - cloudpickle >=0.2.1
    - cytoolz >=0.7.3
    - dask-core {{ version }}
    - distributed >=1.22.0
    - numpy >=1.11.0
    - pandas >=0.19.0
    - partd >=0.3.8
    - toolz >=0.7.3

test:
  imports:
    - dask
    - dask.array
    - dask.bag
    - dask.bytes
    - dask.dataframe
    - dask.dataframe.tseries
    - dask.delayed
    - dask.diagnostics
    - dask.distributed
    - distributed

about:
  home: http://github.com/dask/dask/
  license: BSD 3-Clause
  summary: 'Parallel Python with task scheduling'
  doc_url: https://dask.pydata.org/
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
    - jcrist
    - koverholt
    - martindurant
    - mrocklin
    - pitrou
    - tomaugspurger
    - shoyer
