{% set version = "5.9" %}

package:
  name: ncurses
  version: {{ version }}

source:
  fn: ncurses-{{ version }}.tar.gz
  url: http://ftp.gnu.org/pub/gnu/ncurses/ncurses-{{ version }}.tar.gz
  md5: 8cb9c412e5f2d96bc6f459aa8c6282a1
  patches:
    # http://lists.gnu.org/archive/html/bug-ncurses/2011-04/txtkWQqiQvcZe.txt
    - fix.patch
    # http://lists.gnu.org/archive/html/bug-ncurses/2015-01/msg00016.html
    - ncurses-5.9-gcc-5.patch

build:
  number: 0
  detect_binary_files_with_prefix: true

test:
  commands:
    # Test libraries
    {% set ncurses_libraries = [
        "libncurses",
        "libtinfo",
        "libform",
        "libmenu",
        "libpanel",
    ] %}
    {% for each_ncurses_library in ncurses_libraries %}
    - test -f ${PREFIX}/lib/{{ each_ncurses_library }}.a
    - test -f ${PREFIX}/lib/{{ each_ncurses_library }}w.a
    - test -f ${PREFIX}/lib/{{ each_ncurses_library }}.so
    - test -f ${PREFIX}/lib/{{ each_ncurses_library }}w.so
    {% endfor %}

    # Test include directories
    - test -d ${PREFIX}/include/ncurses
    - test -d ${PREFIX}/include/ncursesw

    # Test headers
    {% set ncurses_headers = [
        "curses.h",
        "cursesapp.h",
        "cursesf.h",
        "cursesm.h",
        "cursesp.h",
        "cursesw.h",
        "cursslk.h",
        "eti.h",
        "etip.h",
        "form.h",
        "menu.h",
        "nc_tparm.h",
        "ncurses.h",
        "ncurses_dll.h",
        "panel.h",
        "term.h",
        "term_entry.h",
        "termcap.h",
        "tic.h",
        "unctrl.h"
    ] %}
    {% for each_ncurses_header in ncurses_headers %}
    - test -L ${PREFIX}/include/ncurses/{{ each_ncurses_header }}
    - test -L ${PREFIX}/include/ncursesw/{{ each_ncurses_header }}
    - test -f ${PREFIX}/include/{{ each_ncurses_header }}
    {% endfor %}

about:
  home: http://www.gnu.org/software/ncurses/
  license: Free software (MIT-like)
  summary: Library for text-based user interfaces

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
