{% set name = "clyent" %}
{% set version = "1.2.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Anaconda-Platform/{{ name }}/archive/{{ version }}.tar.gz
  sha256: a4c33bd70fd3c53f133eb301db7b83acb7cbe6d1e405158b8f5582aa888d3aa3

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - clyent

about:
  home: https://github.com/Anaconda-Platform/clyent
  license: BSD 3-Clause
  summary: Command line client library for windows and posix
  description: |
    Clyent is a python command line utility library for binstar,
    binstar-build, and chalmers.
  doc_url: https://pypi.python.org/pypi/clyent
  doc_source_url: https://github.com/Anaconda-Platform/clyent/blob/master/README.md
  dev_url: hhttps://github.com/Anaconda-Platform/clyent

extra:
  recipe-maintainers:
    - jjhelmus
    - nehaljwani
