{% set version = "0.6.4" %}

package:
  name: gitdb
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gitdb/gitdb-{{ version }}.tar.gz
  sha256: a3ebbc27be035a2e874ed904df516e35f4a29a778a764385de09de9e0f139658

build:
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
  run:
    - python
    - smmap >=0.8.3

test:
  imports:
    - gitdb
    - gitdb.db

about:
  home: https://github.com/gitpython-developers/gitdb
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Git Object Database'

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
