{% set name = "boto3" %}
{% set version = "1.4.8" %}
{% set sha256 = "332c6a17fd695581dd6f9ed825ce13c2d5ee3a6f5e1b079bed0ff7293809faf0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - botocore >=1.5.0,<1.6.0
    - jmespath >=0.7.1,<1.0.0
    - s3transfer >=0.1.10,<0.2.0

test:
  imports:
    - boto3
    - boto3.docs
    - boto3.dynamodb
    - boto3.ec2
    - boto3.resources
    - boto3.s3

about:
  home: http://aws.amazon.com/sdk-for-python/
  dev_url: https://github.com/boto/boto3
  doc_url: https://boto3.readthedocs.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Amazon Web Services SDK for Python
  description: Boto3 makes it easy to integrate you Python application, library or script
    with AWS services. It allows Python developers to write softare that makes
    use of services like Amazon S3 and Amazon EC2.
