{% set version = "1.0.4" %}

package:
  name: conda-build-all
  version: {{ version }}

source:
    fn: conda-build-all_v{{ version }}.tar.gz
    url: https://github.com/conda-tools/conda-build-all/archive/v{{version}}.tar.gz
    sha256: 1a2e6b89858e8a5c6c55dd0fe64e18f7730a203740507f7746149771e22d8784

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python
  entry_points:
    - conda-build-all = conda_build_all.cli:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - gitpython
    - conda >4
    - conda-build >=1.21.7
    - anaconda-client
    - mock

test:
  imports:
    - conda_build_all
  commands:
    - conda build-all --version

about:
  license: BSD 3-clause
  license_file: LICENSE
  home: https://github.com/conda-tools/conda-build-all
  summary: conda build-all is a conda subcommand which allows multiple distributions to be built (and uploaded) in a single command
