{% set version = "1.0.0" %}

package:
  name: cyordereddict
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cyordereddict/cyordereddict-{{ version }}.tar.gz
  sha256: d9b2c31796999770801a9a49403b8cb49510ecb64e5d1e9d4763ed44f2d5a76e

build:
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
  run:
    - python

test:
  imports:
    - cyordereddict
    - cyordereddict.benchmark

about:
  home: https://github.com/shoyer/cyordereddict
  license: MIT
  license_file: LICENSE.txt
  summary: "Cython implementation of Python's collections.OrderedDict."

extra:
  recipe-maintainers:
    - ocefpaf
    - jhamman
