{%set name = "mccabe" %}
{%set version = "0.6.1" %}
{%set hash_type = "sha256" %}
{%set hash_val = "dd8d182285a0fe56bace7f45b5e7d1a6ebcbf524e8f3bd87eb0f125271b8831f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner

  run:
    - python

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/PyCQA/mccabe
  license: MIT
  summary: 'McCabe complexity checker for Python'
