{% set version = "3.0.4" %}

package:
  name: chardet
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/chardet/chardet-{{ version }}.tar.gz
  sha256: 84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - chardetect = chardet.cli.chardetect:main

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python

test:
  imports:
    - chardet
  commands:
    - chardetect --help

about:
  home: https://github.com/chardet/chardet
  license: LGPL2
  license_family: GPL
  license_file: LICENSE
  summary: Universal character encoding detector
  description: |
    chardet is a character encoding auto-detector in Python.
  doc_url: http://chardet.readthedocs.org/
  doc_source_url: https://github.com/chardet/chardet/blob/master/docs/index.rst
  dev_url: https://github.com/chardet/chardet


extra:
  recipe-maintainers:
    - dan-blanchard
    - jschueller
    - sigmavirus24
    - nehaljwani
