{% set version = "0.2.1" %}
{% set sha256 = "be6fa26294733e7489822ded4ae25da5b4824a8a7a0e0c2dccfde596e3489bd6" %}

package:
    name: traittypes
    version: {{ version }}

source:
    fn: traittypes-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/t/traittypes/traittypes-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    noarch: python
    number: 1
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    host:
        - python
        - pip
    run:
        - python
        - traitlets >=4.2.2,<5.0

test:
    imports:
        - traittypes

about:
    home: https://github.com/jupyter-incubator/traittypes
    license: BSD 3-Clause
    summary: Trait types for NumPy, SciPy and friends
    license_file: LICENSE

extra:
    recipe-maintainers:
        - SylvainCorlay
        - jasongrout
        - maartenbreddels
        - vidartf
