{% set name = "pylint" %}
{% set version = "1.6.5" %}
{% set sha256 = "a673984a8dd78e4a8b8cfdee5359a1309d833cf38405008f4a249994a8456719" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  {% set pypi_name = name.replace("_", "-") %}
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - pylint = pylint:run_pylint
    - pylint-gui = pylint:run_pylint_gui
    - epylint = pylint:run_epylint
    - pyreverse = pylint:run_pyreverse
    - symilar = pylint:run_symilar

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - astroid >=1.4.5,<1.5.0
    - backports.functools_lru_cache  # [py27]
    - configparser                   # [py27]
    - six
    - isort >=4.2.5
    - mccabe

test:
  imports:
    - pylint
    - pylint.checkers
    - pylint.extensions
    - pylint.pyreverse
    - pylint.reporters
    - pylint.reporters.ureports

  commands:
    - pylint --help
    # Needs to start a GUI with Tk.
    # So running help is not even an option.
    # Just check that it exists.
    - which pylint-gui
    # Has no help option.
    # Running without arguments is an error.
    # So just check that it exists.
    - which epylint
    - pyreverse --help
    - symilar --help

about:
  home: https://github.com/PyCQA/pylint
  license: GPL 2
  summary: 'python code static checker'
