{% set version = "0.5.1" %}

package:
  name: ptyprocess
  version: {{ version }}

source:
  fn: ptyprocess-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/p/ptyprocess/ptyprocess-{{ version }}.tar.gz
  md5: 94e537122914cc9ec9c1eadcd36e73a1

build:
  number: 0

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - ptyprocess

about:
  home: https://github.com/pexpect/ptyprocess
  license: ISC
  summary: 'Run a subprocess in a pseudo terminal'
