{% set name = "nltk" %}
{% set version = "3.2.4" %}
{% set hash_type = "sha256" %}
{% set hash_val = "8682ae52f5de4f2ba7b77bd78222a38575ad01ef29946214b254dfdf93a3a0eb" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six
    - requests

test:
  imports:
    - nltk
    - nltk.app
    - nltk.ccg
    - nltk.chat
    - nltk.chunk
    - nltk.classify
    - nltk.cluster
    - nltk.corpus
    - nltk.corpus.reader
    - nltk.draw
    - nltk.inference
    - nltk.metrics
    - nltk.misc
    - nltk.parse
    - nltk.sem
    - nltk.sentiment
    - nltk.stem
    - nltk.tag
    - nltk.tbl
    - nltk.test
    - nltk.test.unit
    - nltk.test.unit.translate
    - nltk.tokenize
    - nltk.translate
    - nltk.twitter

about:
  home: http://nltk.org/
  license: Apache 2.0
  license_file: LICENSE.txt
  license_family: Apache
  summary: 'Natural Language Toolkit'
  dev_url: https://github.com/nltk/nltk
  doc_url: http://www.nltk.org/
