{% set version = "7.3.2" %}
{% set sha256 = "3e8706b222a2a043035e3871b09037182ecd5513c647a2705500873fb19dbadd" %}

package:
  name: ipywidgets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipywidgets/ipywidgets-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ipython >=4.0.0
    - ipykernel >=4.5.1
    - traitlets >=4.3.1,<5.0.0
    - nbformat >=4.2.0
    - widgetsnbextension >=3.3.0,<3.4.0

test:
  imports:
    - ipywidgets

about:
  home: https://github.com/ipython/ipywidgets
  license: BSD 3-clause
  license_file: LICENSE
  license_family: BSD
  summary: Jupyter Interactive Widgets
  description: |
    ipywidgets are interactive HTML widgets for Jupyter notebooks and the IPython kernel.
  doc_url: https://ipywidgets.readthedocs.io/en/latest/
  doc_source_url: https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/index.rst

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
    - jasongrout
    - maartenbreddels
    - pbugnion
