{%set name = "click" %}
{%set version = "6.7" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "f15516df478d5a56180fbf80e68f206010e6d160fc39fa508b65e035fd75130b" %}
{%set build_num = "1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - click

about:
  home: http://click.pocoo.org/
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'A simple wrapper around optparse for powerful command line utilities.'
  dev_url: https://github.com/pallets/click
  doc_url: http://click.pocoo.org/

extra:
  recipe-maintainers:
    - pmlandwehr
