{% set version = "1.1.32" %}

package:
  name: libxslt
  version: {{ version }}

source:
  url: ftp://xmlsoft.org/libxml2/libxslt-{{ version }}.tar.gz
  sha256: 526ecd0abaf4a7789041622c3950c0e7f2c4c8835471515fd77eec684a355460

build:
  number: 2
  run_exports:
    # forward compatible: https://abi-laboratory.pro/tracker/timeline/libxslt/
    - {{ pin_subpackage('libxslt') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - icu  # [not win]
    - libxml2
  run:
    - icu  # [not win]
    - libxml2

test:
  commands:
    - xsltproc --version
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://xmlsoft.org/XSLT/
  license: MIT
  license_file: COPYING
  summary: The XSLT C library developed for the GNOME project
  description: |
    "Libxslt is the XSLT C library developed for the GNOME project.
    XSLT itself is a an XML language to define transformation for XML.
    Libxslt is based on libxml2 the XML C library developed for the GNOME project.
    It also implements most of the EXSLT set of processor-portable extensions functions
    and some of Saxon's evaluate and expressions extensions."
  doc_url: http://xmlsoft.org/XSLT/
  doc_source_url: https://github.com/GNOME/libxslt/tree/master/doc

extra:
  recipe-maintainers:
    - ocefpaf
