{% set version = "4.2.13" %}

package:
  name: hdf4
  version: {{ version }}

source:
  url: http://www.hdfgroup.org/ftp/HDF/HDF_Current/src/hdf-{{ version }}.tar.bz2
  sha256: 55d3a42313bda0aba7b0463687caf819a970e0ba206f5ed2c23724f80d2ae0f3
  patches:
    - max_files.patch
    # https://salsa.debian.org/debian-gis-team/hdf4/blob/master/debian/patches/hdfi.h
    - hdfi_h.patch

build:
  number: 2
  run_exports:
    # change SONAMEs with bugfix rev.
    #    https://abi-laboratory.pro/tracker/timeline/hdf5/
    - {{ pin_subpackage('hdf4', max_pin='x.x.x') }}

requirements:
  build:
    - cmake  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bison  # [not win]
    - flex  # [not win]
    - libtool  # [unix]
    - automake  # [unix]
    - autoconf  # [unix]
  host:
    - msinttypes  # [win and vc<14]
    - zlib
    - jpeg
  run:
    - zlib
    - jpeg

test:
  commands:
    - hdiff -V  # [not win]
    - h4_ncgen -V  # [not win]
    - h4_ncdump -V  # [not win]
    - test -f ${PREFIX}/lib/libdf.a  # [not win]
    - test -f ${PREFIX}/lib/libmfhdf.a  # [not win]
    - test -f ${PREFIX}/lib/libdf${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/libmfhdf${SHLIB_EXT}  # [not win]

about:
  home: http://www.hdfgroup.org/HDF4/
  license: BSD-3-Clause
  summary: 'Library and multi-object file format for storing and managing data between machines'
  license_family: BSD
  license_file: COPYING

extra:
  recipe-maintainers:
    - groutr
    - msarahan
    - ocefpaf
