{% set version = "1.0.0" %}

package:
  name: backports.shutil_get_terminal_size
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/backports.shutil_get_terminal_size/backports.shutil_get_terminal_size-{{ version }}.tar.gz
  sha256: 713e7a8228ae80341c70586d1cc0a8caa5207346927e23d09dcbcaf18eadec80

build:
  number: 3
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - backports
  run:
    - python
    - backports

test:
  imports:
    - backports
    - backports.shutil_get_terminal_size

about:
  home: https://github.com/chrippa/backports.shutil_get_terminal_size
  license: MIT
  license_file: LICENSE
  summary: "A backport of the get_terminal_size function from Python 3.3's shutil."

extra:
  recipe-maintainers:
    - ocefpaf
