package:
  name: openblas
  version: 0.2.19

source:
  git_url: https://github.com/xianyi/OpenBLAS.git
  git_tag: v0.2.19

build:
  number: 0

requirements:
  #  run:
  #  - libgfortran

about:
  home: http://www.openblas.net/
  license: BSD
  license_file: LICENSE
  summary: Optimized BLAS library based on GotoBLAS2
  description: |
    OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version.
  doc_url: https://github.com/xianyi/OpenBLAS/wiki
  dev_url: https://github.com/xianyi/OpenBLAS
