{% set version = "4.6.1" %}

package:
  name: ipykernel
  version: {{ version }}

source:
  fn: ipykernel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipykernel/ipykernel-{{ version }}.tar.gz
  sha256: 2e1825aca4e2585b5adb7953ea16e53f53a62159ed49952a564b1e23507205db

build:
  number: 0
  script:
    - pip install --no-deps .
    - python -m ipykernel install --prefix $PREFIX

requirements:
  build:
    - pip
    - python
    - jupyter_client
    - ipython >=4.0
    - tornado >=4.0
  run:
    - python
    - ipython >=4.0
    - traitlets
    - jupyter_client
    - tornado >=4.0

test:
  imports:
    - ipykernel

about:
  home: http://ipython.org
  license: BSD 3-clause
  license_file: COPYING.md
  summary: IPython Kernel for Jupyter
