{% set version = "4.4.1" %}

package:
  name: notebook
  version: {{ version }}

source:
  fn: notebook-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/n/notebook/notebook-{{ version }}.tar.gz
  sha256: dfadef2babd7c04c6c257df7d07d7ba587e503dbb4e4c95305f9a95b8d3a9765


build:
  script: pip install --no-deps .
  number: 0
  entry_points:
    - jupyter-notebook = notebook.notebookapp:main
    - jupyter-nbextension = notebook.nbextensions:main
    - jupyter-serverextension = notebook.serverextensions:main

requirements:
  build:
    - python
    - pip
  run:
    - ipykernel
    - ipython_genutils
    - jinja2
    - jupyter_core
    - jupyter_client
    - nbconvert
    - nbformat
    - python
    - terminado
    - tornado >=4
    - traitlets

test:
  commands:
    - jupyter notebook -h
    - jupyter nbextension -h
    - jupyter serverextension -h
  imports:
    - notebook

about:
  home: http://jupyter.org
  license: BSD 3-clause
  summary: A web-based notebook environment for interactive computing
