{% set version = "1.23.0" %}

package:
  name: distributed
  version: "{{ version }}"

source:
  fn: distributed-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/distributed/distributed-{{ version }}.tar.gz
  sha256: 13b4a6741ac395bf76cfccfd17ede66abca521d8cec96ba83615c1dede36651f

build:
  number: 0
  entry_points:
    - dask-scheduler=distributed.cli.dask_scheduler:go
    - dask-ssh=distributed.cli.dask_ssh:go
    - dask-worker=distributed.cli.dask_worker:go
    - dask-remote=distributed.cli.dask_remote:go
    - dask-submit=distributed.cli.dask_submit:go
    - dask-mpi=distributed.cli.dask_mpi:go
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - click >=6.6
    - cloudpickle >=0.2.2
    - cytoolz >=0.7.4
    - dask-core >=0.18.0
    - futures  # [py2k]
    - msgpack-python
    - psutil
    - pyyaml
    - singledispatch  # [py2k]
    - six
    - sortedcontainers
    - tblib
    - toolz >=0.7.4
    - tornado >=4.5.1
    - zict >=0.1.3

test:
  imports:
    - distributed
    - distributed.cli
    - distributed.comm
    - distributed.deploy
    - distributed.diagnostics
    - distributed.protocol
  commands:
    - dask-scheduler --help
    - dask-ssh --help
    - dask-worker --help

about:
  home: http://distributed.readthedocs.io/en/latest/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Distributed computing with Dask'

extra:
  recipe-maintainers:
    - mrocklin
    - pitrou
    - jcrist
    - martindurant
    - jakirkham
