{% set version = "1.17.0" %}

package:
  name: distributed
  version: "{{ version }}"

source:
  fn: distributed-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/distributed/distributed-{{ version }}.tar.gz
  sha256: d45b241e19d86312435c0877b6242cf499476e1b25fa96b6f5b3a092aebb24fe

build:
  number: 0
  noarch: python
  entry_points:
    - dask-scheduler = distributed.cli.dask_scheduler:go
    - dask-ssh = distributed.cli.dask_ssh:go
    - dask-worker = distributed.cli.dask_worker:go
    - dask-remote = distributed.cli.dask_remote:go
    - dask-submit = distributed.cli.dask_submit:go
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - bokeh >=0.12.3
    - boto3
    - click >=6.6
    - cloudpickle >=0.2.2
    - dask >=0.14.1
    - locket
    - msgpack-python
    - psutil
    - s3fs >=0.0.8
    - six
    - tblib
    - toolz >=0.7.4
    - tornado >=4.2
    - zict >=0.1.2
    - sortedcontainers

test:
  imports:
    - distributed
    - distributed.bokeh
    - distributed.cli
    - distributed.diagnostics
    - distributed.http
  commands:
    - dask-scheduler --help
    - dask-ssh --help
    - dask-worker --help

about:
  home: http://distributed.readthedocs.io/en/latest/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Distributed computing'
