{% set version = "1.16.1" %}

package:
  name: distributed
  version: "{{ version }}"

source:
  fn: distributed-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/distributed/distributed-{{ version }}.tar.gz
  sha256: fdeb2883e5539adbbf1f4853033e209322ecd6f3a8ec43310f4bd196f0684b6d

build:
  number: 0
  noarch: python
  entry_points:
    - dask-scheduler = distributed.cli.dask_scheduler:go
    - dask-ssh = distributed.cli.dask_ssh:go
    - dask-worker = distributed.cli.dask_worker:go
    - dask-remote = distributed.cli.dask_remote:go
    - dask-submit = distributed.cli.dask_submit:go
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - bokeh >=0.12.3
    - boto3
    - click >=6.6
    - cloudpickle >=0.2.2
    - dask >=0.14.0
    - locket
    - msgpack-python
    - psutil
    - s3fs
    - six
    - sortedcollections
    - tblib
    - toolz >=0.7.4
    - tornado >=4.2
    - zict >=0.1.1

test:
  imports:
    - distributed
    - distributed.bokeh
    - distributed.bokeh.status
    - distributed.bokeh.tasks
    - distributed.cli
    - distributed.diagnostics
    - distributed.http
  commands:
    - dask-scheduler --help
    - dask-ssh --help
    - dask-worker --help

about:
  home: http://distributed.readthedocs.io/en/latest/
  license: BSD 3-Clause
  summary: 'Distributed computing'
