{% set version = "1.6.35" %}

package:
  name: libpng
  version: {{ version }}

source:
  url: http://download.sourceforge.net/libpng/libpng-{{ version }}.tar.gz
  sha256: 2b82ab3e996803b80bc73206857e826a155d3ebb374e8eb03a87a63c6f672cf7

build:
  number: 1
  run_exports:
    # SO name changes at minor rev bumps.
    - {{ pin_subpackage('libpng', max_pin='x.x') }}

requirements:
  build:
    - cmake  # [win]
    - libtool  # [not win]
    - automake  # [not win]
    - {{ compiler('c') }}
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - test -f ${PREFIX}/lib/libpng.a  # [not win]
    - test -f ${PREFIX}/lib/libpng${SHLIB_EXT}  # [not win]
    - libpng-config --version  # [not win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.libpng.org/pub/png/libpng.html
  license: zlib/libpng
  license_file: LICENSE
  license_url: http://www.libpng.org/pub/png/src/libpng-LICENSE.txt
  summary: 'PNG reference library'
  description: |
    libpng is the official PNG reference library. It supports almost all PNG
    features, is extensible, and has been extensively tested for over 20 years.
  doc_url: http://www.libpng.org/pub/png/libpng.html
  dev_url: https://sourceforge.net/p/libpng/code/ci/libpng16/tree/

extra:
  recipe-maintainers:
    - ocefpaf
    - msarahan
